mprintf:
	gcc -no-pie -g mprintf.c mprintf.s -o mprintf

five_params:
	gcc -no-pie -g five_params.c five_params.s -o five_params

length:
	gcc -no-pie -g length.c length.s -o length

clean:
	rm -f mprintf length five_params