mprintf:
	gcc -no-pie -g mprintf.c mprintf.s -o mprintf

six_params:
	gcc -no-pie -g six_params.c six_params.s -o six_params

length:
	gcc -no-pie -g length.c length.s -o length

clean:
	rm -f mprintf length six_params